SHOW DATABASES;
USE ejercicio3;

SHOW TABLES;
SHOW COLUMNS FROM asignaturas;
DESCRIBE asignaturas;
SHOW CHARACTER SET;
SHOW COLLATION LIKE 'utf8mb4%';

SHOW CREATE DATABASE ejercicio3;
SHOW CREATE TABLE asignaturas;
SHOW CREATE TABLE ejercicio5.animales;

SHOW CREATE TABLE animales;
SHOW WARNINGS;